# permissions for end users to view clustersilences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustersilence-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: silentstorm
    app.kubernetes.io/part-of: silentstorm
    app.kubernetes.io/managed-by: kustomize
  name: clustersilence-viewer-role
rules:
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - clustersilences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - clustersilences/status
  verbs:
  - get
