---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - alertmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - alertmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - alertmanagers/status
  verbs:
  - get
  - patch
  - update
