# permissions for end users to edit silences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: silence-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: silentstorm
    app.kubernetes.io/part-of: silentstorm
    app.kubernetes.io/managed-by: kustomize
  name: silence-editor-role
rules:
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - silences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - silentstorm.biggold1310.ch
  resources:
  - silences/status
  verbs:
  - get
