apiVersion: silentstorm.biggold1310.ch/v1alpha1
kind: Alertmanager
metadata:
  name: sample-alertmanager
spec:
  address: "http://alertmanager-1.alertmanager.svc.cluster.local:9093"
  silenceSelector:
    matchLabels:
      aminstance: "alertmanager-1"
