apiVersion: silentstorm.biggold1310.ch/v1alpha1
kind: Silence
metadata:
  labels:
    aminstance: alertmanager-1
  name: sample-silence
  namespace: sample-namespace
spec:
  comment: "Silence all KubePodRestart alerts in sample-namespace."
  creator: "namespaceuser@cluster.local"
  matchers:
    - isEqual: true
      isRegex: false
      name: "alertname"
      value: "KubePodRestart"
