// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prometheus/alertmanager/api/v2/client/receiver (interfaces: ClientService)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/alertmanager/receiver/mock.go github.com/prometheus/alertmanager/api/v2/client/receiver ClientService
//

// Package mock_receiver is a generated GoMock package.
package mock_receiver

import (
	reflect "reflect"

	runtime "github.com/go-openapi/runtime"
	receiver "github.com/prometheus/alertmanager/api/v2/client/receiver"
	gomock "go.uber.org/mock/gomock"
)

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// GetReceivers mocks base method.
func (m *MockClientService) GetReceivers(arg0 *receiver.GetReceiversParams, arg1 ...receiver.ClientOption) (*receiver.GetReceiversOK, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReceivers", varargs...)
	ret0, _ := ret[0].(*receiver.GetReceiversOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceivers indicates an expected call of GetReceivers.
func (mr *MockClientServiceMockRecorder) GetReceivers(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivers", reflect.TypeOf((*MockClientService)(nil).GetReceivers), varargs...)
}

// SetTransport mocks base method.
func (m *MockClientService) SetTransport(arg0 runtime.ClientTransport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTransport", arg0)
}

// SetTransport indicates an expected call of SetTransport.
func (mr *MockClientServiceMockRecorder) SetTransport(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTransport", reflect.TypeOf((*MockClientService)(nil).SetTransport), arg0)
}
